services:
  postgres:
    image: postgres:16
    container_name: ecommerce-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  user-service:
    build:
      context: .
      dockerfile: src/UserService/Dockerfile
    container_name: ecommerce-user-service
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./src/UserService/.env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__UserDb: Host=postgres;Port=5432;Database=user_service_db;Username=postgres;Password=yourpassword
    ports:
      - "5204:8080"
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/8080'"]
      interval: 10s
      timeout: 5s
      retries: 10

  product-service:
    build:
      context: .
      dockerfile: src/ProductService/Dockerfile
    container_name: ecommerce-product-service
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./src/ProductService/.env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ProductDb: Host=postgres;Port=5432;Database=product_service_db;Username=postgres;Password=yourpassword
    ports:
      - "5002:8080"
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/8080'"]
      interval: 10s
      timeout: 5s
      retries: 10

  order-service:
    build:
      context: .
      dockerfile: src/OrderService/Dockerfile
    container_name: ecommerce-order-service
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      product-service:
        condition: service_healthy
    env_file:
      - ./src/OrderService/.env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__OrderDb: Host=postgres;Port=5432;Database=order_service_db;Username=postgres;Password=yourpassword
      ServiceUrls__ProductService: http://product-service:8080
    ports:
      - "5136:8080"
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/8080'"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
