// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductService.Data;

#nullable disable

namespace ProductService.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Models.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f06c741-8a2f-47f1-8c74-bf0832f1c101"),
                            Category = "Phones",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flagship Android phone with 6.7-inch OLED display.",
                            ImageUrl = "https://example.com/images/pixel-nova-x.jpg",
                            Name = "Pixel Nova X",
                            Price = 899.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = new Guid("56ea5d5e-6d9f-42ee-9d87-0619cf3e1b02"),
                            Category = "Phones",
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium smartphone with advanced camera stabilization.",
                            ImageUrl = "https://example.com/images/ifruit-pro-14.jpg",
                            Name = "iFruit Pro 14",
                            Price = 1099.00m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("ebf67c77-6991-4f1d-a8e6-353f18d8fe03"),
                            Category = "Phones",
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight smartphone with long battery life.",
                            ImageUrl = "https://example.com/images/galaxy-aero-lite.jpg",
                            Name = "Galaxy Aero Lite",
                            Price = 649.50m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = new Guid("27481f09-16f1-4690-8583-c9f89082a004"),
                            Category = "Laptops",
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "14-inch performance laptop for creators and developers.",
                            ImageUrl = "https://example.com/images/ultrabook-z5.jpg",
                            Name = "UltraBook Z5",
                            Price = 1499.00m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = new Guid("79bcbf88-c1e0-4a0f-9ee4-669ac986f505"),
                            Category = "Laptops",
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Business laptop with robust security and docking support.",
                            ImageUrl = "https://example.com/images/workmate-15.jpg",
                            Name = "WorkMate 15",
                            Price = 1199.99m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = new Guid("de7cbf8d-b151-402e-a13e-3cedf6a60706"),
                            Category = "Laptops",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gaming laptop with dedicated GPU and 240Hz display.",
                            ImageUrl = "https://example.com/images/gamecore-g17.jpg",
                            Name = "GameCore G17",
                            Price = 1899.95m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = new Guid("2ab5bf65-198c-4767-b6f3-89c0c6ace507"),
                            Category = "Accessories",
                            CreatedAt = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Noise-cancelling wireless earbuds with transparency mode.",
                            ImageUrl = "https://example.com/images/pulse-buds-pro.jpg",
                            Name = "Pulse Buds Pro",
                            Price = 199.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = new Guid("64f37d4e-b3ab-4878-85a2-05d7c5aca908"),
                            Category = "Accessories",
                            CreatedAt = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fast USB-C charger compatible with phones and laptops.",
                            ImageUrl = "https://example.com/images/voltcharge-65w.jpg",
                            Name = "VoltCharge 65W",
                            Price = 49.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = new Guid("977ae08c-a68f-48c7-8ccf-b43db4b93809"),
                            Category = "Apparel",
                            CreatedAt = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft cotton-blend hoodie with minimalist design.",
                            ImageUrl = "https://example.com/images/cloudrunner-hoodie.jpg",
                            Name = "CloudRunner Hoodie",
                            Price = 69.00m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = new Guid("1a1608a0-0ca6-4ef8-bbe6-a729e6087810"),
                            Category = "Apparel",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfort-fit t-shirt with breathable fabric.",
                            ImageUrl = "https://example.com/images/devops-tee.jpg",
                            Name = "DevOps Tee",
                            Price = 29.95m,
                            StockQuantity = 140
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
